### ISSUE TITLE
[FEATURE REQUEST] mogelijkheid om magister kalender te importeren

### ISSUE THREAD

**Issue by finnie2006** [Gertje823/magister-scraper#1]
mogelijkheid om magister kalender te importeren naar google kalender

**Comment by Gertje823** [comment]
Op dit moment heb ik geen actief magister account tot mijn beschikking. Ik heb een script geschreven en getest met oude magister roosters. Dit lijkt te werken. Zou je kunnen testen of dit voor jou ook werkt? Aangezien ik het niet echt in het doel van dit script vond passen heb ik een nieuwe repo aangemaakt. [Gertje823/magister2google](https://github.com/Gertje823/magister2google) Als je ergens tegen aan loopt kan je daar een issue openen. Ik zal dit issue sluiten.
